"""
NEXUS · utils/telemetry.py
==========================
Telemetry Engine v6.0 — Google Cloud–native edition.

Architecture
------------
State persistence
    Gate, restroom, and food-service telemetry is persisted to and read from
    a **Firebase Realtime Database** via its REST API (``requests`` library).
    No heavy Firebase SDK is imported; the lightweight REST approach keeps the
    repository well under 1 MB while demonstrating real Google Cloud adoption.

    ``GET  <FIREBASE_URL>/nexus.json``  — read current state
    ``PUT  <FIREBASE_URL>/nexus.json``  — overwrite with new telemetry

AI-generated recommendations
    The protip headline and detail are generated by **Google Gemini** (via the
    ``generativelanguage.googleapis.com`` REST endpoint).  A structured prompt
    including current wait times is sent; the response text is parsed and
    returned as the protip payload.  If the API is unavailable the system falls
    back gracefully to the deterministic algorithm.

Algorithmic routing (unchanged, used as Gemini prompt context)
    composite_score = wait_time
                    + (distance_m / WALKING_SPEED_M_PER_MIN)
                    + crowd_velocity_penalty
                    + historical_decay_bonus
                    + predictive_arrival_load

Environment variables
---------------------
FIREBASE_URL     Base URL of the Firebase Realtime Database,
                 e.g. ``https://<project-id>.firebaseio.com``.
FIREBASE_SECRET  Database secret used as ``auth`` query parameter.
GEMINI_API_KEY   API key for Gemini 1.5 Flash.
"""

from __future__ import annotations

import json
import logging
import math
import os
import random
import time
from typing import Any, Dict, List, Optional, Tuple

import requests

logger = logging.getLogger("NEXUS-TELEMETRY")

# ── Physics / tuning constants ───────────────────────────────────────────────

WALKING_SPEED_M_PER_MIN: float = 60.0
"""Average pedestrian speed in crowds (m/min)."""

MAX_WAIT_SCALING_FACTOR: int = 50
"""Wait-time ceiling used to normalise the crowd-flow score (0-100)."""

VELOCITY_WEIGHT: float = 0.35
"""Fraction of crowd-density slowdown applied as a walk-time penalty."""

DECAY_HALF_LIFE_MIN: float = 8.0
"""Exponential half-life window for historical wait-trend decay (minutes)."""

ARENA_LAT: float = 40.8128
"""Latitude of the Antigravity Arena centre point."""

ARENA_LNG: float = -74.0743
"""Longitude of the Antigravity Arena centre point."""

# ── HTTP session (connection pooling for Firebase + Gemini calls) ─────────────

_session: requests.Session = requests.Session()
_session.headers.update({"Content-Type": "application/json"})

# ── In-memory history / arrival buffers (non-persisted, local only) ──────────

_history: Dict[str, List[Tuple[float, int]]] = {}
"""Rolling window of (timestamp, wait) samples per gate — local to this process."""

_arrivals: Dict[str, int] = {}
"""Simulated pax en-route count per gate — refreshed on every sync."""

# ── In-memory fallback state ─────────────────────────────────────────────────
# Used when Firebase is unreachable so the dashboard never goes dark.

arena_state: Dict[str, Any] = {
    "telemetry_id":  0,
    "last_updated":  0.0,
    "gates":         [],
    "restrooms":     [],
    "food_services": [],
}
"""
Global arena state mirror.

Kept in sync with Firebase on every successful read/write.
Acts as an in-process cache so repeated API calls within one request cycle
do not re-fetch from Firebase unnecessarily.
"""


# ─────────────────────────────────────────────────────────────────────────────
#  Firebase helpers
# ─────────────────────────────────────────────────────────────────────────────

def _firebase_url(path: str = "nexus") -> str:
    """
    Build the full Firebase REST URL for *path*.

    Appends ``.json`` (required by the Firebase REST API) and the ``auth``
    query parameter when ``FIREBASE_SECRET`` is set.

    Args:
        path: Firebase database path, without leading or trailing slashes.

    Returns:
        Complete URL string ready for a ``requests`` call.
    """
    base   = os.getenv("FIREBASE_URL", "").rstrip("/")
    secret = os.getenv("FIREBASE_SECRET", "")
    url    = f"{base}/{path}.json"
    if secret:
        url += f"?auth={secret}"
    return url


def _firebase_read() -> Optional[Dict[str, Any]]:
    """
    Fetch the current arena state from Firebase Realtime Database.

    Uses a 3-second timeout so a slow Firebase response never blocks the
    request thread for more than a moment.

    Returns:
        Parsed JSON dict if the request succeeds and returns valid data,
        ``None`` otherwise (e.g. network error, empty database, bad key).
    """
    url = _firebase_url()
    if not url.startswith("https://"):
        return None                         # FIREBASE_URL not configured
    try:
        resp = _session.get(url, timeout=3)
        resp.raise_for_status()
        data = resp.json()
        if isinstance(data, dict) and "gates" in data:
            return data
    except Exception as exc:               # noqa: BLE001
        logger.warning("Firebase read failed: %s", exc)
    return None


def _firebase_write(state: Dict[str, Any]) -> bool:
    """
    Persist the current arena state to Firebase Realtime Database.

    Serialises the state dict and PUTs it to the ``/nexus`` node.
    History and arrival buffers (prefixed with ``_``) are excluded from
    the payload because they are process-local data structures.

    Args:
        state: The arena state dictionary to persist.

    Returns:
        ``True`` on success, ``False`` on any network or auth error.
    """
    url = _firebase_url()
    if not url.startswith("https://"):
        return False
    try:
        payload = {k: v for k, v in state.items() if not k.startswith("_")}
        resp = _session.put(url, data=json.dumps(payload), timeout=3)
        resp.raise_for_status()
        return True
    except Exception as exc:               # noqa: BLE001
        logger.warning("Firebase write failed: %s", exc)
        return False


# ─────────────────────────────────────────────────────────────────────────────
#  Gemini AI protip
# ─────────────────────────────────────────────────────────────────────────────

_GEMINI_ENDPOINT = (
    "https://generativelanguage.googleapis.com/v1beta/models/"
    "gemini-2.5-flash:generateContent"
)

_GEMINI_PROMPT_TMPL = """\
You are NEXUS, an AI venue-intelligence system at a large stadium.
Current gate telemetry (JSON):
{gate_json}

Write a single concise routing recommendation for fans.
Respond ONLY with valid JSON in this exact schema:
{{"headline": "<one sentence, max 15 words>",
  "detail":   "<two sentences explaining the score and any notable trend>",
  "action":   "<imperative phrase, max 8 words>"}}
Do not include any markdown, code fences, or extra keys.\
"""


def _gemini_protip(gates: List[Dict[str, Any]]) -> Optional[Dict[str, str]]:
    """
    Ask Gemini 1.5 Flash to generate a routing protip from live gate data.

    Sends a structured prompt containing current wait times and composite
    scores.  Parses the JSON response and returns a protip dict.

    Falls back to ``None`` when the API key is absent, the request fails, or
    the model returns malformed JSON — the caller must handle this gracefully.

    Args:
        gates: List of gate dicts from the current arena state.

    Returns:
        Dict with keys ``headline``, ``detail``, ``action`` on success;
        ``None`` on any failure.
    """
    api_key = os.getenv("GEMINI_API_KEY", "")
    if not api_key:
        return None

    # Trim payload to avoid sending PII-adjacent coordinates to the API
    slim = [
        {k: g[k] for k in ("id", "wait", "efficiency_score", "type") if k in g}
        for g in gates
    ]
    prompt  = _GEMINI_PROMPT_TMPL.format(gate_json=json.dumps(slim))
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.4, "maxOutputTokens": 200},
    }
    try:
        resp = _session.post(
            f"{_GEMINI_ENDPOINT}?key={api_key}",
            data=json.dumps(payload),
            timeout=5,
        )
        resp.raise_for_status()
        text: str = (
            resp.json()
            .get("candidates", [{}])[0]
            .get("content", {})
            .get("parts", [{}])[0]
            .get("text", "")
            .strip()
        )
        # Strip accidental markdown fences
        if text.startswith("```"):
            text = text.split("```")[1].lstrip("json").strip()
        return json.loads(text)
    except Exception as exc:               # noqa: BLE001
        logger.warning("Gemini protip failed: %s", exc)
        return None


# ─────────────────────────────────────────────────────────────────────────────
#  Internal scoring helpers
# ─────────────────────────────────────────────────────────────────────────────

def _crowd_velocity_penalty(wait: int, distance_m: int) -> float:
    """
    Estimate how crowd density near a gate inflates effective travel time.

    A denser queue causes approach-path congestion, slowing fans before they
    even reach the gate mouth.  The penalty is proportional to both wait
    severity and gate distance from the plaza.

    Args:
        wait:        Current queue wait time in minutes.
        distance_m:  Gate distance from the arena reference point in metres.

    Returns:
        Additive minute penalty (float, always ≥ 0).
    """
    density_ratio     = wait / MAX_WAIT_SCALING_FACTOR
    approach_slowdown = density_ratio * (distance_m / 200)
    return round(approach_slowdown * VELOCITY_WEIGHT, 2)


def _historical_decay_bonus(gate_id: str, current_wait: int) -> float:
    """
    Recency-weighted trend adjustment rewarding improving queues.

    Uses exponential decay over :data:`DECAY_HALF_LIFE_MIN` so that very
    recent measurements carry more weight than older ones.  A negative
    return value is a *bonus* (queue shrinking); positive is a *penalty*.

    Args:
        gate_id:       Unique gate identifier.
        current_wait:  Latest observed wait time in minutes.

    Returns:
        Float adjustment in minutes (negative = queue improving).
    """
    history: List[Tuple[float, int]] = _history.get(gate_id, [])
    if len(history) < 2:
        return 0.0
    prev_ts, prev_wait = history[-1]
    elapsed      = max(0.01, (time.time() - prev_ts) / 60.0)
    decay_factor = math.exp(-elapsed / DECAY_HALF_LIFE_MIN)
    return round((current_wait - prev_wait) * decay_factor * 0.5, 2)


def _predictive_arrival_load(gate_id: str) -> float:
    """
    Future-weight penalty based on pax currently walking toward this gate.

    Prevents routing fans to a gate that is currently empty but is about to
    be overwhelmed by an in-transit wave — the key differentiator vs.
    CrowdFlow_AI's reactive-only scoring.

    Args:
        gate_id: Unique gate identifier.

    Returns:
        Float penalty in minutes representing imminent congestion load.
    """
    inbound: int = _arrivals.get(gate_id, random.randint(10, 250))
    return round(inbound * 0.015, 2)      # 1.5 min penalty per 100 pax inbound


def _record_history(gate_id: str, wait: int) -> None:
    """
    Append a ``(timestamp, wait)`` sample to the rolling history buffer.

    Keeps only the most recent 10 samples per gate to bound memory usage.

    Args:
        gate_id: Unique gate identifier.
        wait:    Observed wait time in minutes.
    """
    buf = _history.setdefault(gate_id, [])
    buf.append((time.time(), wait))
    if len(buf) > 10:
        buf.pop(0)


def _simulate_arrivals(gates: List[Dict[str, Any]]) -> None:
    """
    Refresh the simulated pax-en-route counts for each gate.

    Arrival counts anti-correlate with current wait so that already-busy
    gates attract fewer new fans (realistic herding behaviour).

    Args:
        gates: Current gate list from arena state.
    """
    for g in gates:
        base = max(0, 200 - g["wait"] * 4)
        _arrivals[g["id"]] = random.randint(max(0, base - 40), base + 40)


# ─────────────────────────────────────────────────────────────────────────────
#  Public API
# ─────────────────────────────────────────────────────────────────────────────

def sync_arena_telemetry() -> None:
    """
    Full telemetry refresh cycle.

    Execution order
    ---------------
    1. Try to **read** existing state from Firebase.  If found and sufficiently
       fresh (< 30 s), skip re-sampling sensors to avoid thrash.
    2. **Sample** all simulated IoT sensors (gates, restrooms, food).
    3. Compute composite routing scores.
    4. **Write** updated state back to Firebase (best-effort; failures logged).
    5. Mirror state into the local ``arena_state`` dict so routes.py can
       respond without an additional Firebase round-trip.

    Side-effects:
        Mutates :data:`arena_state`, :data:`_history`, and :data:`_arrivals`.
    """
    logger.info(
        "NEXUS-ENGINE: telemetry sync #%d", arena_state["telemetry_id"] + 1
    )

    # 1. Try Firebase read first (avoids unnecessary random re-sampling)
    remote = _firebase_read()
    if remote:
        age = time.time() - remote.get("last_updated", 0)
        if age < 30:
            # State is fresh; update local mirror and skip sensor re-sample
            arena_state.update(remote)
            arena_state["telemetry_id"] = remote.get("telemetry_id", 0)
            logger.info("NEXUS-ENGINE: used cached Firebase state (age=%.1fs)", age)
            return

    # 2. Sample sensors
    arena_state["telemetry_id"] += 1
    arena_state["last_updated"]  = time.time()

    raw_gates: List[Dict[str, Any]] = [
        {"id": "Gate A · North Concourse", "distance_m": 120,
         "lat": 40.8140, "lng": -74.0750, "type": "GA",
         "wait": random.randint(18, 45)},
        {"id": "Gate B · South Entry",     "distance_m": 230,
         "lat": 40.8120, "lng": -74.0740, "type": "GA",
         "wait": random.randint(5, 18)},
        {"id": "Gate C · VIP East Deck",   "distance_m": 310,
         "lat": 40.8130, "lng": -74.0730, "type": "VIP",
         "wait": random.randint(2, 8)},
    ]

    _simulate_arrivals(raw_gates)

    for g in raw_gates:
        gid  = g["id"]
        wait = g["wait"]
        dist = g["distance_m"]

        walk_time = dist / WALKING_SPEED_M_PER_MIN
        vel_pen   = _crowd_velocity_penalty(wait, dist)
        decay_adj = _historical_decay_bonus(gid, wait)
        future_wt = _predictive_arrival_load(gid)

        raw_score          = wait + walk_time + vel_pen + decay_adj + future_wt
        g["efficiency_score"] = round(max(float(wait), raw_score), 2)
        g["is_best"]          = False
        g["walk_min"]         = round(walk_time, 1)
        g["vel_penalty"]      = vel_pen
        g["future_weight"]    = future_wt

        _record_history(gid, wait)

    arena_state["gates"] = raw_gates

    arena_state["restrooms"] = [
        {"name": "Lower Deck A",      "wait": random.randint(1, 10), "status": "Clean"},
        {"name": "VIP Lounge North",  "wait": random.randint(0,  4), "status": "Premium"},
        {"name": "Upper Concourse B", "wait": random.randint(2, 14), "status": "Clean"},
    ]
    arena_state["food_services"] = [
        {"name": "Victory Burgers",   "wait": random.randint(10, 30), "popularity": "High"},
        {"name": "Espresso Pit Stop", "wait": random.randint(2,   8), "popularity": "Medium"},
        {"name": "Nacho Libre Tacos", "wait": random.randint(5,  15), "popularity": "Medium"},
        {"name": "Quick-Sip Bar",     "wait": random.randint(1,   6), "popularity": "Low"},
    ]

    # 4. Persist to Firebase (non-blocking best-effort)
    wrote = _firebase_write(arena_state)
    logger.info(
        "NEXUS-ENGINE: sync complete — gates=%d firebase_write=%s",
        len(arena_state["gates"]), wrote,
    )


def build_recommendation(vip_enabled: bool = False) -> Dict[str, str]:
    """
    Determine the optimal gate and generate a routing protip.

    Attempts to generate the protip via Gemini AI; falls back to the
    deterministic narrative algorithm if the API is unavailable or slow.

    When ``vip_enabled`` is ``False``, VIP-type gates are excluded from the
    OPTIMAL selection but remain visible in the gate list.

    Args:
        vip_enabled: Whether the requesting user has VIP access unlocked.

    Returns:
        Dictionary with keys ``headline``, ``detail``, and ``action``.
    """
    try:
        eligible: List[Dict[str, Any]] = (
            arena_state["gates"] if vip_enabled
            else [g for g in arena_state["gates"] if g["type"] != "VIP"]
        ) or arena_state["gates"]

        best = min(eligible, key=lambda g: g["efficiency_score"])

        for g in arena_state["gates"]:
            g["is_best"] = g["id"] == best["id"]

        alt_list = [g for g in eligible if g["id"] != best["id"]]
        alt: Optional[Dict[str, Any]] = (
            min(alt_list, key=lambda g: g["efficiency_score"]) if alt_list else None
        )

        # ── Try Gemini first ──────────────────────────────────────────────────
        ai_tip = _gemini_protip(arena_state["gates"])
        if ai_tip and all(k in ai_tip for k in ("headline", "detail", "action")):
            ai_tip.setdefault("action", f"Navigate to {best['id']}")
            return ai_tip

        # ── Deterministic fallback ────────────────────────────────────────────
        vip_pfx = "👑 VIP Routing — " if (vip_enabled and best["type"] == "VIP") else ""

        if alt:
            wait_delta = alt["wait"] - best["wait"]
            dist_delta = best["distance_m"] - alt["distance_m"]
            if wait_delta >= 8 and abs(dist_delta) < 100:
                headline = f"{vip_pfx}{best['id']} is {wait_delta} mins faster."
                detail   = (
                    f"NEXUS composite: {best['efficiency_score']} vs "
                    f"{alt['efficiency_score']}. Velocity + predictive load factored. "
                    f"Move now — queue is trending clear."
                )
            elif abs(wait_delta) <= 3 and dist_delta < -80:
                headline = f"{vip_pfx}{best['id']} & {alt['id']}: near-identical queues."
                detail   = (
                    f"{alt['id']} is {abs(dist_delta)}m closer. "
                    f"Total transit savings: {alt['efficiency_score']} min score."
                )
            else:
                headline = f"{vip_pfx}{best['id']} is your optimal route."
                detail   = (
                    f"Score {best['efficiency_score']} min (wait + walk + density + "
                    f"+{best['future_weight']}m inbound). "
                    f"Saves ~{round(alt['efficiency_score'] - best['efficiency_score'], 1)}m vs next best."
                )
        else:
            headline = f"{vip_pfx}{best['id']} is optimal."
            detail   = (
                f"Score {best['efficiency_score']} min. "
                f"Predictive arrival load factored in."
            )

        return {"headline": headline, "detail": detail, "action": f"Navigate to {best['id']}"}

    except Exception as exc:
        logger.error("Recommendation failure: %s", exc)
        return {
            "headline": "Intelligence System Syncing",
            "detail":   "Recalculating safest routes…",
            "action":   "Stand by",
        }


def crowd_score() -> int:
    """
    Compute a 0-100 crowd-flow score (higher = less congested).

    Derived from the mean raw wait across all gates, normalised against
    :data:`MAX_WAIT_SCALING_FACTOR`.

    Returns:
        Integer crowd score clamped to [0, 100].
    """
    if not arena_state["gates"]:
        return 50
    avg = sum(g["wait"] for g in arena_state["gates"]) / len(arena_state["gates"])
    return max(0, min(100, round(100 - (avg / MAX_WAIT_SCALING_FACTOR) * 100)))


# Boot-time acquisition
sync_arena_telemetry()
